name: CI

on: [push]

jobs:
  lint_black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install -r requirements.txt
      - uses: psf/black@stable
        with:
            options: "--check --verbose"
            src: "./src"
            version: "~= 22.0"
  lint_ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -r requirements.txt
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py311 .
  lint_isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
          pip install -r requirements.txt
      - name: Lint with ruff
        run: |
          isort **/*.py -c
  lint_pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2  
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x
      - name: Python Pip Install
        uses: logikal-code/pip-install@v1.0.0
      - name: Python Lint
        run: |
          echo "::add-matcher::.github/matchers/pylint-error.json"
          echo "::add-matcher::.github/matchers/pylint-warning.json"
          pip install pylint
          pylint --output-format=colorized src/lennybot